import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
      { type: "autogenerated", dirName: "." },
      {
        type: 'category',
        label: 'Audit Reports',
        items: [
            {
                type: 'link',
                label: 'Helixbox LnBridge',
                href: 'https://github.com/helix-bridge/contracts/blob/master/helix-contract/audit/2024-07-04%20Audit%20Report%20-%20Helix%20Bridge%20v1.0.pdf',
            },
            {
                type: 'link',
                label: 'XToken',
                href: 'https://github.com/helix-bridge/xtoken-monorepo/blob/main/packages/xtoken-contract/audit/2024-07-04%20Audit%20Report%20-%20Helix%20xToken%20v1.0.pdf',
            }
        ],
      },
  ],
};

export default sidebars;
